package swe.kne.chip08;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import swe.kne.chip08.chip8.Cpu;
import swe.kne.chip08.chip8.Decoder;
import swe.kne.chip08.chip8.Graphics;
import swe.kne.chip08.chip8.Memory;

/**
 * autogenerated by libgdx's own project generator, not touched by me.
 */
public class chip08mainwindow extends ApplicationAdapter {

	private Cpu cpu = new Cpu();

	//private Graphics graphics = new Graphics();
	//private Memory memory = new Memory();
	// Decoder decoder = new Decoder();
	
	@Override
	public void create () {
		;
	}

	@Override
	public void render () {
		;
	}
	
	@Override
	public void dispose () {
		;
	}
}
