package swe.kne.chip08.desktop;

import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration;
import swe.kne.chip08.chip08mainwindow;

/**
 * autogenerated by libgdx's own project generator, i've just changed it to lwjgl3 to stop
 * a bunch of warnings.
 */
public class DesktopLauncher {
	public static void main (String[] arg) {
		Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
		config.setTitle("chip 0 8");
		config.setWindowedMode(512, 256); // original resolution: 64 x 32, in this case, it's * 8.
		new Lwjgl3Application(new chip08mainwindow(), config);
	}
}